# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_remove_alertresponse_alerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.BigIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
