# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
