# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20161201_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.CharField(max_length=128),
        ),
    ]
